clf;clc;
close all;
clear;
%%
% example file path
efspath = '../EX_DATA/';
% example file for reading in
% HHZ component the southern California network recording
% the 2019 Ridgecrest earthquake, -60 seconds to 300 seconds
% after the origin time
efsname_o = 'EFS_Example.efs';
% example file to write EFS file with the Matlab function write_structure2efs
efsname_2 = 'EFS_Test2.efs';
% example file to write EFS file from the irisFetch data structure 
efsname_3 = 'EFS_Example_Matlab.efs';
% example EFS file that is generated by the Fortran codes
efsname_Fortran = '10056345.efs';

%% Reading in an EFS file generated by the Fortran codes
itype = 2;
efsStruct_Fortran = load_efs(['../Fortran/' efsname_Fortran],itype);
%% Reading in and writing out an EFS file generated by the Python codes
itype = 1;
efsStruct1=load_efs([efspath,efsname_o],itype);
iosuc1 =write_structure2efs(efspath,efsname_2,efsStruct1,itype);

% comparing records from the two EFS files
efsStruct2=load_efs([efspath,efsname_2],itype);
figure(1);clf;
plot(efsStruct1.waveforms(1).data,'k-');
hold on;
plot(efsStruct1.waveforms(1).data,'r--');
box on;

%% Downloading data with MATLAB from IRIS and saving the data in the EFS format
% using irisFetch to download data for an example station ADO
evtdatenum0 = datenum([2019, 7, 6, 3, 19, 53]);
daylen = 86400;
starttime = evtdatenum0-1/daylen*1*60;
endtime = evtdatenum0+1/daylen*5*60;
sstr = datestr(starttime,'yyyy-mm-dd HH:MM:SS');
edtr = datestr(endtime,'yyyy-mm-dd HH:MM:SS');
irisSTR = irisFetch.Traces('CI','ADO','*','HHZ',sstr, edtr);

% saving the data as an EFS file
iosuc3 =write_iris2efs(efspath,efsname_3,irisSTR,itype);

% comparing the records from two EFS files
efsStruct3=load_efs([efspath,efsname_3],itype);
figure(2);clf;
plot(efsStruct1.waveforms(1).data(2:end),'k-');
hold on;
plot(efsStruct3.waveforms(1).data,'r--');
box on;
